github:
  user_or_org: nk53
  repo_name: "stanalyzer-feedstock"
  branch_name: master
  tooling_branch_name: master
clone_depth: 0
recipe_dir: recipe
noarch_platforms: linux_64
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows
